id: I0AA77BE0
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W30303
  source: bdrc.io
  batch_id: batch003
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.7
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-11-01T09:25:26.991585+00:00'
last_modified: '2022-11-01T09:25:26.991591+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W30303
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30303
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དབང་ཆེན་དགྱེས་རབ་རྡོ་རྗེ།
  languages:
  - bo
  author: དབང་ཆེན་དགྱེས་རབ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9938996498594848
  ocr_word_median_confidence_index: 1.0
quality: null
bases:
  I6060:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6060
      total_pages: 1014
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I6060.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9938996498594848
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
